Cache already generated table.
gabrielcsapo/turtler pull request #8
Opened 2017-12-28 03:55 UTC by anusaini

Rationale:

We generate tables out of data passed to us. If user again requests same table, we generate it again. Which is not necessary.

This PR saves the outcome of first computation and returns that in subsequent invocations.

2017-12-28 04:17 UTC, gabrielcsapo requested changes

2017-12-28 04:17 UTC, gabrielcsapo commented on index.js
> +    if (!this.asciiTable) {
why not make this a 

```js
if(this.asciiTable) return this.asciiTable
```

2017-12-28 04:17 UTC, gabrielcsapo commented on index.js
> +    if (!this.markdownTable) {
why not make this a 

```js
if(this.markdownTable) return this.markdownTable
```

It is a smaller change and doesn't make the code hard to decipher.

2017-12-28 04:17 UTC, gabrielcsapo commented on index.js
> +      this.markdownTable = table;
if you implement the suggestion it could be 

```js
return this.markdownTable = table;
```

2017-12-28 04:17 UTC, gabrielcsapo commented on index.js
> +      this.asciiTable = table;
if you implement the suggestion it could be 

```js
return this.asciiTable = table;
```

2017-12-28 05:42 UTC, anusaini commented
No reason. Just different style.

2017-12-28 05:45 UTC, anusaini commented
Done.

2017-12-29 02:55 UTC, gabrielcsapo approved these changes

2017-12-29 02:55 UTC, gabrielcsapo commented
awesome! @anusaini

2017-12-29 02:55 UTC, merged